[app]
address = "0.0.0.0:9000"
admin_username = "admin"
admin_password = "admin_dev_change_me"

[db]
host = "postgres"
port = 5432
user = "sa9"
password = "sa9_dev_password"
database = "listmonk"
ssl_mode = "disable"
max_open = 25
max_idle = 25
max_lifetime = "300s"
